const S = require('strings').S;
module.exports = {
	location:[S.FORMATTED_ADDRESS,S.LAT, S.LNG, S.STREET_NUMBER, S.POLITICAL, S.ROUTE, S.LOCALITY, S.POSTAL_TOWN, S.POSTAL_CODE, S.ADMINISTRATIVE_AREA_LEVEL_1, S.ADMINISTRATIVE_AREA_LEVEL_2, S.COUNTRY, S.PREMISE,
	S.QUADS],
	
	interview:[S.ABOUT_FREE_TYPE,S.AGE,S.NICKNAME,S.HEADLINE],
	
physical:[
	S.BODY_TYPE,S.BRA_CUP_SIZE, S.ETHNICITY, S.CHEST_SIZE,S.DRESS_SIZE,
	S.ETHNICITY,S.EYE_COLOUR,S.HEIGHT, S.LEG_LENGTH, S.HAIR_LENGTH,S.HAIR_COLOUR,S.HIPS_MEASUREMENT,
	S.PUBIC_HAIR, S.PIERCINGS,S.SHOE_SIZE,S.SMOKER,S.TATTOOS,S.WAIST_SIZE, S.WEIGHT],
	
personality:[S.AMBITIOUS,S.BIRTH_ORDER,S.CAR, S.DRINK, S.HARD_DRUGS,
	S.INTENT, S.INTEREST_PEOPLE_WITH_CHILDREN, S.I_AM_LOOKING_FOR,
	S.LONGEST_RELATIONSHIP, S.MARITAL_STATUS, S.PERSONALITY,
	S.PROFESSION, S.PROSTITUTES, S.RELIGION, S.SMOKE_WEED, S.HAVE_CHILDREN, S.WANT_CHILDREN,
	S.INTERESTS,
	S.ADULT_PARTIES,S.ANAL,S.ANAL_PLAY,S.BAREBACK,S.B_D_S_M,S.B_D_S_M_GIVING,S.B_D_S_M_RECEIVING,S.BLINDFOLDS,
	S.BUKKAKE,S.CAR_MEETS,S.C_I_M,S.CROSS_DRESSING,S.CUCKOLDING,S.CYBERSEX,S.DEEP_THROAT,S.DEPILATION,S.DISABLED,S.DOGGING,S.DOMINATION,
	S.DOMINATION_GIVING,S.DOMINATION_RECEIVING,S.DOUBLE_PENETRATION,S.ENEMA,S.EXHIBITIONISM,S.FACE_SITTING,S.FACIALS,
	S.FEMALE_EJACULATION,S.FETISH,S.F_F_M_3_SOMES,S.FILMING,S.FINGERING,S.FISTING,S.FISTING_GIVING,S.FISTING_RECEIVING,
	S.FOOD_SEX_SPLOSHING,S.FOOT_WORSHIP,S.FRENCH_KISSING,S.GANG_BANGS,S.GROUP_SEX,S.HAND_RELIEF,S.HUMILIATION,
	S.HUMILIATION_GIVING,S.HUMILIATION_RECEICING,S.SPANKING_GIVING,S.LAP_DANCING,S.MAKING_VIDEOS,S.MASOCHISM,
	S.MASSAGE,S.MILKING_LACTATING,S.M_M_F_3SOMES,S.MODELING,S.MORESOMES,S.NATURISM_NUDISM,S.ORAL,
	S.PENETRATION_PROTECTED,S.PERIOD_PLAY,S.PHONE_SEX,S.POLE_DANCING,S.PREGNANT,S.PROSTATE_MASSAGE,
	S.PUSSY_PUMPING,S.RECEIVING_ORAL,S.RIMMING,S.RIMMING_GIVING,S.RIMMING_RECEICING,S.ROLE_PLAY_AND_FANTASY,
	S.SADISM,S.SAME_ROOM_SWAPPING,S.SAUNA_BATH_HOUSES,S.SMOKING_FETISH,S.SNOWBALLING,S.SOFT_SWING,S.SPANKING,
	S.SPANKING_RECEIVING,S.STRAP_ON,S.STRIPTEASE,S.SUB_GAMES,S.SWALLOW,S.SWINGERS_CLUBS,S.SWINGING,S.SYBIAN_AND_MACHINE_SEX,
	S.TAKING_PHOTOS,S.TANTRIC,S.THREESOMES,S.TIE_AND_TEASE,S.TOYS,S.UNIFORMS,S.UNPROTECTED_SEX,S.VOYEURISM,S.WATERSPORTS_GIVING,
	S.WATERSPORTS_RECEIVING,S.WEBCAMS],
	
multimediaCategory:[S.MULTIMEDIA_ID,S.MULTIMEDIA_CATEGORY_ID,S.TITLE,S.CAPTION,S.IS_ME, S.TAGS]
};